apiVersion: v1
kind: Service
metadata:
  name: sammo-fight-iq
  labels:
    app: sammo-fight-iq
    app.kubernetes.io/name: sammo-fight-iq
    app.kubernetes.io/component: backend
spec:
  selector:
    app: sammo-fight-iq
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
  sessionAffinity: None
